package com.epicness.alejandria;

public enum ModuleID {

    ALPHA_MASKING,
    LAYERED_MASKING,
    MASKING,
    SHAPE_RENDERER_MASKING,
    SIMPLE_ANIMATION,
    ADVANCED_MASK,
    ANIMATED_BACKGROUNDS,
    A_STAR,
    ORTHOGRAPHIC_EXAMPLE
}